### ISSUE TITLE
Is "FFT_compression_for_N210.bin" fpga file renamed as "u2plus.bin" ?

### ISSUE THREAD

**Issue by pcabreracamara** [ucsdsysnet/sparsdr#5]
Hi all,

I'm testing these days this amazing project. After compile everything with no errors, in the `sparsdr/fpga_images/N210` folder there is only on file named `u2plus.bin`, and  no file named as the getting started guide states; `FFT_compression_for_N210.bin`.

I want to be sure, as after the first seconds the "SparSDR" example gets completely hanged/frozen.

Thank you very much in advance,
Pedro

**Comment by samcrow** [comment]
Yes, the file name was incorrect. I changed it to FFT_compression_for_N210.bin. Thanks for reporting.
