### ISSUE TITLE
Providing an IQZ example file

### ISSUE THREAD

**Issue by florianeckert** [ucsdsysnet/sparsdr#7]
I'm facing issues with either the reconstructor or receiver, but cannot narrow down the problem. Would it be possible to provide an IQZ example file which has been recorded with the SparSDR receiver and can be correctly reconstructed with the SparSDR reconstructor?

**Comment by samcrow** [comment]
Here's an example file: https://github.com/ucsdsysnet/sparsdr/tree/master/examples/sparsdr_receive

Sorry for the long delay in responding to this.
